name: Trictionary Auto Build

on:
  push:
    paths:
      - 'keywords.txt'
  schedule:
    - cron: '0 * * * *'  # 매 정각마다 실행 (UTC 기준)

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: 리포지토리 체크아웃
      uses: actions/checkout@v3

    - name: Python 설정
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: 의존성 설치
      run: pip install requests beautifulsoup4

    - name: 빌드 스크립트 실행
      run: python build.py

    - name: 변경 사항 커밋 및 푸시
      run: |
        git config --global user.name "github-actions"
        git config --global user.email "actions@github.com"
        git add entries/*.html entry_list.json
        git commit -m "자동 빌드: keywords.txt 업데이트 또는 스케줄 실행" || echo "변경 사항 없음"
        git push
